// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  communitySidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      href: 'https://discord.gg/U9SJAHU',
      label: 'Discordへ参加',
    },
  ],
}

module.exports = sidebars
